#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: 2659038eaa1b
#
Name     : libspatialite
Version  : 5.1.0
Release  : 11
URL      : https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-5.1.0.tar.gz
Source0  : https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-5.1.0.tar.gz
Summary  : Spatial SQL database engine based on SQLite
Group    : Development/Tools
License  : GPL-2.0 MPL-1.1
Requires: libspatialite-lib = %{version}-%{release}
Requires: libspatialite-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : geos-dev
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(rttopo)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(zlib)
BuildRequires : proj-dev
BuildRequires : sqlite-autoconf-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Remove-deprecated-xmlNanoHTTP-calls.patch

%description
--------------------- libspatialite ------------------------
PLEASE read the following information.

%package dev
Summary: dev components for the libspatialite package.
Group: Development
Requires: libspatialite-lib = %{version}-%{release}
Provides: libspatialite-devel = %{version}-%{release}
Requires: libspatialite = %{version}-%{release}
Requires: librttopo-dev
Requires: libxml2-dev
Requires: proj-dev
Requires: sqlite-autoconf-dev

%description dev
dev components for the libspatialite package.


%package lib
Summary: lib components for the libspatialite package.
Group: Libraries
Requires: libspatialite-license = %{version}-%{release}

%description lib
lib components for the libspatialite package.


%package license
Summary: license components for the libspatialite package.
Group: Default

%description license
license components for the libspatialite package.


%prep
%setup -q -n libspatialite-5.1.0
cd %{_builddir}/libspatialite-5.1.0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720029701
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-freexl \
--disable-minizip
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720029701
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libspatialite
cp %{_builddir}/libspatialite-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libspatialite/fac7e08b00d48464e5cff0180701395569184413 || :
cp %{_builddir}/libspatialite-%{version}/src/control_points/COPYING %{buildroot}/usr/share/package-licenses/libspatialite/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/spatialite.h
/usr/include/spatialite/control_points.h
/usr/include/spatialite/debug.h
/usr/include/spatialite/gaia_network.h
/usr/include/spatialite/gaia_topology.h
/usr/include/spatialite/gaiaaux.h
/usr/include/spatialite/gaiaconfig-msvc.h
/usr/include/spatialite/gaiaconfig-msvc.h.in
/usr/include/spatialite/gaiaconfig.h
/usr/include/spatialite/gaiaconfig.h.in
/usr/include/spatialite/gaiaexif.h
/usr/include/spatialite/gaiageo.h
/usr/include/spatialite/gaiamatrix.h
/usr/include/spatialite/geojson.h
/usr/include/spatialite/geopackage.h
/usr/include/spatialite/gg_advanced.h
/usr/include/spatialite/gg_const.h
/usr/include/spatialite/gg_core.h
/usr/include/spatialite/gg_dxf.h
/usr/include/spatialite/gg_dynamic.h
/usr/include/spatialite/gg_formats.h
/usr/include/spatialite/gg_mbr.h
/usr/include/spatialite/gg_sequence.h
/usr/include/spatialite/gg_structs.h
/usr/include/spatialite/gg_wfs.h
/usr/include/spatialite/gg_xml.h
/usr/include/spatialite/spatialite_ext.h
/usr/include/spatialite/sqlite.h
/usr/include/spatialite/stored_procedures.h
/usr/lib64/libspatialite.so
/usr/lib64/mod_spatialite.so
/usr/lib64/pkgconfig/spatialite.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspatialite.so.8
/usr/lib64/libspatialite.so.8.1.0
/usr/lib64/mod_spatialite.so.8
/usr/lib64/mod_spatialite.so.8.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libspatialite/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/libspatialite/fac7e08b00d48464e5cff0180701395569184413
